language: php
php:
  - 5.5
  - 5.6

notifications:
  email:
    - fenix440@gmail.com

branches:
  only:
    - master

before_script:
   - composer self-update
   - composer install --dev --prefer-source
   - pwd
   - ls -al

script: "`pwd`/vendor/bin/codecept run -c `pwd`/codeception.travis.yml"