#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Fenix440\Resource\Commands\TemplateCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new TemplateCommand());
$application->run();