#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

use BSzala\Scaffold\Commands\TemplateCommand;
use BSzala\Scaffold\Contracts\ApplicationStates;
use Symfony\Component\Console\Application;

$application = new Application(ApplicationStates::NAME,ApplicationStates::VERSION);
$application->add(new TemplateCommand());
$application->add(new \BSzala\Scaffold\Commands\VimConfigurationInstallCommand());
$application->run();



