#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else if(file_exists(__DIR__.'/../autoload.php')) {
    require __DIR__.'/../autoload.php';
}else{
        require __DIR__.'/vendor/autoload.php';
}

use Fenix440\Scaffold\Commands\TemplateCommand;
use Fenix440\Scaffold\Contracts\ApplicationStates;
use Symfony\Component\Console\Application;

$application = new Application(ApplicationStates::NAME,ApplicationStates::VERSION);
$application->add(new TemplateCommand());
$application->run();